"use client";

import { useState } from "react";
import Link from "next/link";
import { Button, StatusBadge } from "./ui";
import { Icon } from "./icons";

export function ConnectionForm() {
  const [testState, setTestState] = useState<"idle" | "testing" | "success">("idle");
  const [connected, setConnected] = useState(false);
  function test() { setTestState("testing"); window.setTimeout(() => setTestState("success"), 900); }
  if (connected) return <div className="mx-auto max-w-2xl rounded-xl border border-emerald-200 bg-white p-8 text-center shadow-sm"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Icon name="check" className="h-7 w-7"/></div><h2 className="mt-5 text-2xl font-bold">Databricks Connected Successfully</h2><p className="mt-2 text-sm text-slate-500">Your workspace is ready for this ValPerf demonstration.</p><dl className="mx-auto mt-7 max-w-md divide-y divide-slate-100 rounded-lg border border-slate-200 text-left text-sm"><div className="flex justify-between p-4"><dt className="text-slate-500">Connection Name</dt><dd className="font-semibold">Production Databricks</dd></div><div className="flex justify-between p-4"><dt className="text-slate-500">Workspace</dt><dd className="font-semibold">Demo Workspace</dd></div><div className="flex justify-between p-4"><dt className="text-slate-500">Status</dt><dd><StatusBadge tone="success">Connected</StatusBadge></dd></div><div className="flex justify-between p-4"><dt className="text-slate-500">Last Sync</dt><dd className="font-semibold">Just now</dd></div></dl><Link href="/dashboard" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-5 py-3 text-sm font-semibold text-white hover:bg-indigo-700">Go to Dashboard <Icon name="arrow"/></Link></div>;
  const input = "mt-2 w-full rounded-lg border border-slate-300 px-3.5 py-2.5 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10";
  return <div className="mx-auto max-w-3xl rounded-xl border border-slate-200 bg-white shadow-sm"><form className="p-6 sm:p-8" onSubmit={e => e.preventDefault()}><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Connection Name<input className={input} defaultValue="Production Databricks"/></label><label className="text-sm font-medium text-slate-700">Cloud Provider<select className={input} defaultValue="Azure Databricks"><option>Azure Databricks</option><option>AWS Databricks</option><option>GCP Databricks</option></select></label><label className="text-sm font-medium text-slate-700 sm:col-span-2">Databricks Workspace URL<input className={input} defaultValue="https://adb-xxxxxxxx.azuredatabricks.net"/></label><label className="text-sm font-medium text-slate-700">Account ID<input className={input} placeholder="00000000-0000-0000-0000-000000000000"/></label><label className="text-sm font-medium text-slate-700">Client ID<input className={input} placeholder="Enter OAuth client ID"/></label><label className="text-sm font-medium text-slate-700 sm:col-span-2">Client Secret<input type="password" className={input} placeholder="Enter OAuth client secret"/></label></div><div className="mt-6 rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-800">For production, ValPerf will use secure OAuth machine-to-machine authentication. Credentials shown in this POC are for demonstration only.</div>{testState !== "idle" && <div className={`mt-5 flex items-center gap-2 rounded-lg p-3 text-sm font-medium ${testState === "success" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{testState === "testing" ? <span className="h-4 w-4 animate-spin rounded-full border-2 border-slate-300 border-t-indigo-600"/> : <Icon name="check" className="h-4 w-4"/>}{testState === "testing" ? "Testing connection..." : "Connection successful"}</div>}<div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button variant="secondary" disabled={testState === "testing"} onClick={test}>{testState === "testing" ? "Testing..." : "Test Connection"}</Button><Button onClick={() => setConnected(true)}>Connect Databricks</Button></div></form></div>;
}
