import type { IconName } from "./icons";
import { Icon } from "./icons";

export function PageHeader({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{title}</h1><p className="mt-1.5 text-sm text-slate-500">{description}</p></div>{action}</div>; }
export function MetricCard({ label, value, detail, icon = "trend" }: { label: string; value: string; detail?: string; icon?: IconName }) { return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-start justify-between"><div className="rounded-lg bg-indigo-50 p-2.5 text-indigo-600"><Icon name={icon}/></div><span className="text-xs font-medium text-slate-400">Current</span></div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight text-slate-950">{value}</p>{detail && <p className="mt-2 text-xs text-slate-500">{detail}</p>}</article>; }
export function StatusBadge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "success" | "warning" | "danger" | "neutral" }) { const colors = { success: "bg-emerald-50 text-emerald-700 ring-emerald-600/20", warning: "bg-amber-50 text-amber-700 ring-amber-600/20", danger: "bg-rose-50 text-rose-700 ring-rose-600/20", neutral: "bg-slate-100 text-slate-600 ring-slate-500/20" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${colors[tone]}`}>{children}</span>; }
export function DataTable({ headers, rows }: { headers: string[]; rows: React.ReactNode[][] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{headers.map((h, i) => <th key={h} className={`px-5 py-3 font-semibold ${i === headers.length - 1 ? "text-right" : ""}`}>{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row, i) => <tr key={i} className="transition hover:bg-slate-50">{row.map((cell, j) => <td key={j} className={`px-5 py-4 ${j === headers.length - 1 ? "text-right font-semibold" : ""}`}>{cell}</td>)}</tr>)}</tbody></table></div>; }
export function SectionCard({ title, subtitle, children, className = "" }: { title: string; subtitle?: string; children: React.ReactNode; className?: string }) { return <section className={`rounded-xl border border-slate-200 bg-white shadow-sm ${className}`}><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">{title}</h2>{subtitle && <p className="mt-0.5 text-sm text-slate-500">{subtitle}</p>}</div>{children}</section>; }
export function Button({ children, variant = "primary", type = "button", disabled = false, onClick }: { children: React.ReactNode; variant?: "primary" | "secondary" | "danger"; type?: "button" | "submit"; disabled?: boolean; onClick?: () => void }) { const styles = { primary: "bg-indigo-600 text-white hover:bg-indigo-700", secondary: "border border-slate-300 bg-white text-slate-700 hover:bg-slate-50", danger: "border border-rose-200 bg-white text-rose-600 hover:bg-rose-50" }; return <button type={type} disabled={disabled} onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold shadow-sm transition disabled:cursor-not-allowed disabled:opacity-60 ${styles[variant]}`}>{children}</button>; }
